# Generated by Django 3.2.6 on 2023-10-18 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/course_photos/'),
            preserve_default=False,
        ),
    ]
